<a href="https://colab.research.google.com/github/AishwaryaGhorpade/Data-Science/blob/main/03_EDA/HandlingNullValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/market_data.csv')

uding info we can get the infomation about the dataset,and here we can see the null nall values columns also
example:total rows are 8523 but Item_weight and outlet_size we got less rows means those column have null values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

One more way of finding null values using isnull() method ,this method returns the total numbers of null values have in that column use the sum method

In [8]:
df.isnull()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,False,False,False,False,False,False,False,False,False,False,False,False
8519,False,False,False,False,False,False,False,False,True,False,False,False
8520,False,False,False,False,False,False,False,False,False,False,False,False
8521,False,False,False,False,False,False,False,False,False,False,False,False
8522,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

# Handling Missing Values

1. **Deleting colum**n:if colum have more missing values and that column is not defendent to other column then delete that column is the best way of handling null values.
dropna(axis=1) helps to delete null values column

problem:this is not best way if column have less null values,because if we delte entire data ,we can miss the valuable information from the column.

In [10]:
column_delete_df=df.dropna(axis=1)

In [11]:
column_delete_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Fat_Content           8523 non-null   object
 2   Item_Visibility            8523 non-null   float64
 3   Item_Type                  8523 non-null   object
 4   Item_MRP                   8523 non-null   float64
 5   Outlet_Identifier          8523 non-null   object
 6   Outlet_Establishment_Year  8523 non-null   int64
 7   Outlet_Location_Type       8523 non-null   object
 8   Outlet_Type                8523 non-null   object
 9   Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 666.0+ KB

2.**Deleting Row:** deleting the which have null values using dropna(axis=0)
In this case,there are better posibility of getting better accuracy than before.This might me because of coulumn may contain more valuevable information than we expected.

In [12]:
row_delete_df=df.dropna(axis=0)

In [13]:
row_delete_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4650 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            4650 non-null   object
 1   Item_Weight                4650 non-null   float64
 2   Item_Fat_Content           4650 non-null   object
 3   Item_Visibility            4650 non-null   float64
 4   Item_Type                  4650 non-null   object
 5   Item_MRP                   4650 non-null   float64
 6   Outlet_Identifier          4650 non-null   object
 7   Outlet_Establishment_Year  4650 non-null   int64
 8   Outlet_Size                4650 non-null   object
 9   Outlet_Location_Type       4650 non-null   object
 10  Outlet_Type                4650 non-null   object
 11  Item_Outlet_Sales          4650 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 472.3+ KB

# Filling the missing values-Imputation

In this case, we will be filling the missing values with a certain number.

The possible ways to do this are:

Filling the missing data with the mean or median value if it's a numerical variable.

Filling the missing data with mode if it's a categorical value.

Filling the numerical value with 0 or -999, or some other number that will not occur in the data. This can be done so that the machine can recognize that the data is not real or is different.

Filling the categorical value with a new type for the missing values.

for numerical values, we can impute with mean and median
for catgorical data we can impute with mode

In [14]:
df['Item_Weight'].mean()

np.float64(12.857645184135976)

In [15]:
df['Item_Weight'].median()

12.6

Fiiling with **mean** values,
when we have less ouliers then its better to use **mean**

In [22]:
fill_values_df=df
fill_values_df['Item_Weight']=fill_values_df['Item_Weight'].fillna(df['Item_Weight'].mean())

In [23]:
fill_values_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
 12  IItem_Weight               8523 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 865.7+ KB

filling with **median**,
when we have more outliers then its better way to fill **meadian**

In [24]:
fill_median_df=df
fill_median_df['Item_Weight']=fill_median_df['Item_Weight'].fillna(df['IItem_Weight'].median())

In [25]:
fill_median_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
 12  IItem_Weight               8523 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 865.7+ KB

# Forward and backword filling -Imputation

1.Forward Fiiling using ffill

In [28]:
forward_filling_df=df
forward_filling_df['Outlet_Size']=forward_filling_df['Outlet_Size'].ffill()

In [29]:
forward_filling_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                8523 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
 12  IItem_Weight               8523 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 865.7+ KB

2.backward filling using bfill

In [30]:
backward_filling_df=df
backward_filling_df['Outlet_Size']=backward_filling_df['Outlet_Size'].bfill()

In [31]:
backward_filling_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                8523 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                8523 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
 12  IItem_Weight               8523 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 865.7+ KB